###=========================================================
### GGIEMH API Testing
###=========================================================

### Health Check @ Root
# GET /
# Sends status code 200.

GET {{localBaseUrl}}