###=========================================================
### GGIEMH API Testing
###=========================================================

### Health Check @ Root
# GET /
# Sends status code 200.

GET {{localBaseUrl}}

### Get All Homes
# GET /homes
# Sends a list of all homes in the database.

GET {{localBaseUrl}}/homes

### Get Single Home
# GET /homes/:id
# Sends a single home by id.

GET {{localBaseUrl}}/homes/1

### Test 404
GET {{localBaseUrl}}/helloworld

### Test 400
GET {{localBaseUrl}}/homes/-1